apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-todo-demo
spec:
  selector:
    matchLabels:
      app: spring-boot-todo-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-todo-demo
    spec:
      containers:
        - name: spring-boot-todo-demo
          image: yolanv/sb-todo-demo
          ports:
            - containerPort: 8080
